version: '3.9'

services:
  database:
    container_name: calendar-db
    image: mysql:latest
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mago_database
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - calendar-db:/var/lib/mysql

  phpmyadmin:
    container_name: calendar-phpmyadmin
    image: phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    environment:
      PMA_HOST: database
    ports:
      - 8080:80
    depends_on:
      - database

volumes:
  calendar-db:
